kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: order
spec:
  maxReplicas: 7
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order
  targetCPUUtilizationPercentage: 50
