kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: msa
spec:
  maxReplicas: 7
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: product
    apiVersion: apps/v1
  targetCPUUtilizationPercentage: 75
